### ISSUE TITLE
Latest version of Pillow breaks current implementation in postprocess_reactions

### ISSUE THREAD

**Issue by schinto** [thomas0809/RxnScribe#1]
**Bug:**
Pillow 10.0.0 removed ANTIALIAS from PIL.Image. Current implementation requires 9.5.0, however the requirements.txt currently allows for 10.0.0 to be installed.
**Logs:**
```
Traceback (most recent call last):
  File "/home/user/rxnscribe-test/RxnScribe/predict.py", line 21, in <module>
    main()
  File "/home/user/rxnscribe-test/RxnScribe/predict.py", line 17, in main
    print(model.predict_image_file(args.image_path, molscribe=True, ocr=True))
  File "/home/user/rxnscribe-test/RxnScribe/rxnscribe/interface.py", line 123, in predict_image_file
    predictions = self.predict_image_files([image_file], **kwargs)
  File "/home/user/rxnscribe-test/RxnScribe/rxnscribe/interface.py", line 120, in predict_image_files
    return self.predict_images(input_images, **kwargs)
  File "/home/user/rxnscribe-test/RxnScribe/rxnscribe/interface.py", line 102, in predict_images
    reactions = postprocess_reactions(
  File "/home/user/rxnscribe-test/RxnScribe/rxnscribe/data.py", line 359, in postprocess_reactions
    text = ocr.readtext(bbox.image(), detail=0)
  File "/home/user/scratch/conda/envs/rxnscribe/lib/python3.9/site-packages/easyocr-1.7.0-py3.9.egg/easyocr/easyocr.py", line 464, in readtext
    result = self.recognize(img_cv_grey, horizontal_list, free_list,\
  File "/home/user/scratch/conda/envs/rxnscribe/lib/python3.9/site-packages/easyocr-1.7.0-py3.9.egg/easyocr/easyocr.py", line 383, in recognize
    image_list, max_width = get_image_list(h_list, f_list, img_cv_grey, model_height = imgH)
  File "/home/user/scratch/conda/envs/rxnscribe/lib/python3.9/site-packages/easyocr-1.7.0-py3.9.egg/easyocr/utils.py", line 613, in get_image_list
    crop_img,ratio = compute_ratio_and_resize(crop_img,width,height,model_height)
  File "/home/user/scratch/conda/envs/rxnscribe/lib/python3.9/site-packages/easyocr-1.7.0-py3.9.egg/easyocr/utils.py", line 576, in compute_ratio_and_resize
    img = cv2.resize(img,(int(model_height*ratio),model_height),interpolation=Image.ANTIALIAS)
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
```
**Solution:**
Update requirements.txt to
```
torch
numpy>=1.19.5
pandas>=1.2.4
Pillow==9.5.0
matplotlib>=3.5.3
opencv-python>=4.5.5.64
pycocotools==2.0.4
pytorch-lightning>=1.8.6
transformers>=4.5.1
huggingface-hub>=0.11.0
MolScribe @ git+https://github.com/thomas0809/MolScribe.git@main#egg=MolScribe
easyocr>=1.6.2
```

**Comment by thomas0809** [comment]
Hi,

Thank you for pointing out this issue and providing a solution! 

As the log suggests, the error was caused by the incompatibility between easyocr and Pillow 10.0.0. This issue has been fixed by the latest version of easyocr. https://github.com/JaidedAI/EasyOCR/commit/caf88774f673774079c681d77d2314c986431104

**Comment by thomas0809** [comment]
Updated requirements.txt according to the suggestion.
