### ISSUE TITLE
pretrained ckpts

### ISSUE THREAD

**Issue by CYF2000127** [thomas0809/RxnScribe#2]
Hi, thanks for your great contribution! I would like to ask where could I download the pretrained ckpts checkpoint_e299_ap370.pth? Thank you.

**Comment by thomas0809** [comment]
Hi,

It's available at https://github.com/gaopengcuhk/Pretrained-Pix2Seq

**Comment by CYF2000127** [comment]
thank you very much! However, I met another error:
Traceback (most recent call last):
  File "main.py", line 370, in <module>
    main()
  File "main.py", line 357, in main
    trainer.fit(model, datamodule=dm, ckpt_path=ckpt_path)
  File "/home/chenyufan/anaconda3/envs/rxn/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/home/chenyufan/anaconda3/envs/rxn/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 36, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/home/chenyufan/anaconda3/envs/rxn/lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 88, in launch
    return function(*args, **kwargs)
  File "/home/chenyufan/anaconda3/envs/rxn/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/home/chenyufan/anaconda3/envs/rxn/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1103, in _run
    results = self._run_stage()
  File "/home/chenyufan/anaconda3/envs/rxn/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1182, in _run_stage
    self._run_train()
  File "/home/chenyufan/anaconda3/envs/rxn/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1195, in _run_train
    self._run_sanity_check()
  File "/home/chenyufan/anaconda3/envs/rxn/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1267, in _run_sanity_check
    val_loop.run()
  File "/home/chenyufan/anaconda3/envs/rxn/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/chenyufan/anaconda3/envs/rxn/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 152, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/home/chenyufan/anaconda3/envs/rxn/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/chenyufan/anaconda3/envs/rxn/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 137, in advance
    output = self._evaluation_step(**kwargs)
  File "/home/chenyufan/anaconda3/envs/rxn/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 234, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "/home/chenyufan/anaconda3/envs/rxn/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1485, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/chenyufan/anaconda3/envs/rxn/lib/python3.8/site-packages/pytorch_lightning/strategies/ddp.py", line 359, in validation_step
    return self.model(*args, **kwargs)
  File "/home/chenyufan/anaconda3/envs/rxn/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/chenyufan/anaconda3/envs/rxn/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1156, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/chenyufan/anaconda3/envs/rxn/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1110, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "/home/chenyufan/anaconda3/envs/rxn/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/chenyufan/anaconda3/envs/rxn/lib/python3.8/site-packages/pytorch_lightning/overrides/base.py", line 110, in forward
    return self._forward_module.validation_step(*inputs, **kwargs)
  File "main.py", line 248, in validation_step
    pred_seqs, pred_scores = self.model(images, max_len=self.tokenizer[format].max_len)
  File "/home/chenyufan/anaconda3/envs/rxn/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/chenyufan/RxnScribe-main/rxnscribe/pix2seq/pix2seq.py", line 44, in forward
    features, pos = self.backbone(image_tensor)
  File "/home/chenyufan/anaconda3/envs/rxn/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/chenyufan/RxnScribe-main/rxnscribe/pix2seq/backbone.py", line 107, in forward
    pos.append(self[1](x).to(x.tensors.dtype))
  File "/home/chenyufan/anaconda3/envs/rxn/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/chenyufan/RxnScribe-main/rxnscribe/pix2seq/position_encoding.py", line 38, in forward
    y_embed = not_mask.cumsum(1, dtype=torch.float32)
RuntimeError: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True)'. You can turn off determinism just for this operation, or you can use the 'warn_only=True' option, if that's acceptable for your application. You can also file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation.
Can you help me check about it? And I would ask which version of Torch are you using? Thank you very much.

**Comment by thomas0809** [comment]
The code was implemented with torch 1.11.0.

Please take a look at https://discuss.pytorch.org/t/cumsum-cuda-kernel-determinism/168820

**Comment by CYF2000127** [comment]
But with RTX3090 and RTX4090, it seem does not support torch version below 1.13.0, and  Using version 1.13.0 and above will result in errors, which is an inevitable issue for recent graphics cards. Is there any alternative solution?
